# Generated by Django 3.2 on 2021-05-03 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_badge', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_promo', models.CharField(max_length=50)),
                ('discount_promo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_produk', models.CharField(choices=[('Baju', 'Baju'), ('Celana', 'Celana'), ('Topi', 'Topi'), ('Aksesoris', 'Aksesoris')], max_length=200)),
                ('nama_produk', models.CharField(max_length=200, null=True)),
                ('harga_produk', models.CharField(max_length=50, null=True)),
                ('diskon_produk', models.CharField(blank=True, max_length=5, null=True)),
                ('deskripsi_produk', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('freq_shop_user', models.CharField(max_length=20)),
                ('badge_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='badge_membership.badgename')),
                ('nama_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge_membership.toko')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gratis_ongkir', models.CharField(max_length=120)),
                ('code_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge_membership.promocode')),
                ('freq_shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge_membership.profile')),
                ('nama_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge_membership.badgename')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
