# Generated by Django 3.2 on 2021-05-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge_membership', '0002_auto_20210502_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badge',
            new_name='BadgeName',
        ),
    ]
